Repository enzomoy/rest-api, pull requests merged in 2024-04, with the labels that each got.

#13 add github workflow for testing the app
  .github/workflows/continuous-integration.yml
Labels: enhancement

#16 change the branch of the workflow activation
  .github/workflows/continuous-integration.yml
Labels: bug

#17 fix readme problems
  README.md
Labels: bug

#19 Modify docker-compose to have better dependencies using healthcheck
  docker-compose.yml
Labels: bug

#21 Edit mysql healthcheck in docker-compose.yml
  docker-compose.yml
Labels: bug

#26 Docker
  docker-compose.yml
  src/index.js
Labels: bug

#27 add docker start
  README.md
Labels: bug, documentation
